apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      tier: frontend
  replicas: 4
  template:
    metadata: 
      name:  nginx
      labels:
        app: nginx
        type: ecommerce
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:1.16.0